# Generated by Django 5.1 on 2024-08-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/'),
        ),
    ]
