# Generated by Django 5.1 on 2024-08-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_creator', '0002_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='max_contributions',
            field=models.IntegerField(default=10),
        ),
    ]
